language: elixir
sudo: false
elixir:
  - 1.2.6
  - 1.3.2
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 18.3
  - 19.0
before_script:
  - kerl list installations
matrix:
  exclude:
    - otp_release: 19.0
      elixir: 1.1.1
